name: Build Geode Mod (Android Only)

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Android 32-bit
          target: android32

        - name: Android 64-bit
          target: android64

    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          cli: "latest"
          sdk: "v5.7.1"
          target: ${{ matrix.config.target }}

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - uses: actions/upload-artifact@v4
        with:
          name: zBot-Android-Build
          path: ${{ steps.build.outputs.build-output }}
